[project]
name = "resume-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "streamlit>=1.45.0",
    "streamlit-ace>=0.1.1",
]
